# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b9dd909b008aa9797fae2adfa39d83b7f9c8164903f683e4e90dd64c8912add16869134ee5edabecc6d8e2e04e6e34a565a721217724becdb2434e6b5721ade8

test:
  secret_key_base: a95d724e856128cd4e11cb86c4a487b34fc30f91f1577acf03ba1fd8a28d191c292fe5a4603a98919bd0cc09384a75c6cf140e33bbbdb0f520659ce9ba4a2485

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
